### ISSUE TITLE
[issue] API 문서 초기 작성

### ISSUE THREAD

**Issue by Jiwook00** [codestates/Mohaji-server#1]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: git book을 활용한 API 문서 작성

### TODO
~~1. [ ] 문서 위키에 올리기~~

2. [x] 요청에 따른 req, res 작성
3. [x] 형식 통일하기(signup)
4. [x] 구글 로그인에서 어떤 값을 받을 수 있을지
5. [x] 태그 등 body 값 object, string 구분하기
6. [x] GET 메서드 쿼리문으로

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Urgency: `High`
