### ISSUE TITLE
[issue] DB 스키마 수정 사항 및 체크리스트

### ISSUE THREAD

**Issue by Jiwook00** [codestates/Mohaji-server#26]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: '설명'

### TODO
1. [x] config 파일과 .env.example 구성 깔끔하게 정리
~~2. [ ] DB 스키마 수정 => comment(spot_id) -> playSpot(id) 관계 정리 필요 (하나를 바라보게)~~
3. [x] DB 관계도 구성 마무리(commneter 생성 X)
4. [x] 크롤링 or 카카오API 이용할지 최대한 빨리 결정  (카카오-클라이언트-서버 workflow)
5. [x] 만들어 둔 테이블 다시 수정(NULL 부분 다시 확인하고 수정 필요)
