### ISSUE TITLE
[issue] 소셜 로그인 학습하기(2)

### ISSUE THREAD

**Issue by Jiwook00** [codestates/Mohaji-server#28]
### ISSUE
- Group:  `server`
- Type: `study`
- Detail: '구글 소셜 로그인을 구현하기 위한 학습'

### TODO
1. [x] 구글 소셜로그인 Flow 이해하기
2. [x] passport 사용 방법 이해하기
3. [ ] 각각의 메서드 역할 이해하기
